# -*- coding: utf-8 -*-

# Auto-generated minimal OCP cable defaults (CU baseline)

OCP_CABLE_DEFAULTS = {15: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '2',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '12',
             'wire_hot_size': '12',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 20: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '2',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '12',
             'wire_hot_size': '12',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 25: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '2',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '10',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 30: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '2',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '10',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 35: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '8',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 40: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '8',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 45: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '8',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 50: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '8',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 60: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '10',
             'wire_hot_size': '6',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 70: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '8',
             'wire_hot_size': '4',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 80: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '1/0',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '8',
             'wire_hot_size': '4',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 90: {'AL': None,
      'CU': {'conduit_type': 'EMT',
             'max_lug_qty': 1,
             'max_lug_size': '350',
             'number_of_parallel_sets': 1,
             'wire_ground_size': '8',
             'wire_hot_size': '2',
             'wire_insulation': 'THWN',
             'wire_material': 'CU',
             'wire_service_ground_size': '8',
             'wire_temperature_rating': '75 C'}},
 100: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '8',
              'wire_hot_size': '2',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '8',
              'wire_temperature_rating': '75 C'}},
 110: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '6',
              'wire_hot_size': '2',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '6',
              'wire_temperature_rating': '75 C'}},
 125: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '6',
              'wire_hot_size': '1',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '6',
              'wire_temperature_rating': '75 C'}},
 150: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '6',
              'wire_hot_size': '1/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '6',
              'wire_temperature_rating': '75 C'}},
 175: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '6',
              'wire_hot_size': '2/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '4',
              'wire_temperature_rating': '75 C'}},
 200: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '6',
              'wire_hot_size': '3/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '4',
              'wire_temperature_rating': '75 C'}},
 225: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '350',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '4',
              'wire_hot_size': '4/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 250: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '500',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '4',
              'wire_hot_size': '250',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 300: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '600',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '4',
              'wire_hot_size': '350',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 350: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 2,
              'max_lug_size': '600',
              'number_of_parallel_sets': 1,
              'wire_ground_size': '3',
              'wire_hot_size': '500',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '1/0',
              'wire_temperature_rating': '75 C'}},
 400: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 3,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '3',
              'wire_hot_size': '3/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '4',
              'wire_temperature_rating': '75 C'}},
 450: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 3,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '2',
              'wire_hot_size': '4/0',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 500: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 3,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '2',
              'wire_hot_size': '250',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 600: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 3,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '1',
              'wire_hot_size': '350',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '2',
              'wire_temperature_rating': '75 C'}},
 700: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 3,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '1/0',
              'wire_hot_size': '500',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '1/0',
              'wire_temperature_rating': '75 C'}},
 800: {'AL': None,
       'CU': {'conduit_type': 'EMT',
              'max_lug_qty': 4,
              'max_lug_size': '600',
              'number_of_parallel_sets': 2,
              'wire_ground_size': '1/0',
              'wire_hot_size': '500',
              'wire_insulation': 'THWN',
              'wire_material': 'CU',
              'wire_service_ground_size': '1/0',
              'wire_temperature_rating': '75 C'}},
 1000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 4,
               'max_lug_size': '600',
               'number_of_parallel_sets': 3,
               'wire_ground_size': '2/0',
               'wire_hot_size': '400',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 1200: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 4,
               'max_lug_size': '600',
               'number_of_parallel_sets': 3,
               'wire_ground_size': '3/0',
               'wire_hot_size': '600',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 1600: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 6,
               'max_lug_size': '600',
               'number_of_parallel_sets': 4,
               'wire_ground_size': '4/0',
               'wire_hot_size': '600',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 2000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 8,
               'max_lug_size': '600',
               'number_of_parallel_sets': 5,
               'wire_ground_size': '250',
               'wire_hot_size': '600',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 2500: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 15,
               'max_lug_size': '750',
               'number_of_parallel_sets': 6,
               'wire_ground_size': '350',
               'wire_hot_size': '600',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 3000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 15,
               'max_lug_size': '750',
               'number_of_parallel_sets': 8,
               'wire_ground_size': '400',
               'wire_hot_size': '500',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 4000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 15,
               'max_lug_size': '750',
               'number_of_parallel_sets': 10,
               'wire_ground_size': '500',
               'wire_hot_size': '600',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '1/0',
               'wire_temperature_rating': '75 C'}},
 5000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 15,
               'max_lug_size': '750',
               'number_of_parallel_sets': 11,
               'wire_ground_size': '700',
               'wire_hot_size': '750',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '2/0',
               'wire_temperature_rating': '75 C'}},
 6000: {'AL': None,
        'CU': {'conduit_type': 'PVC',
               'max_lug_qty': 16,
               'max_lug_size': '750',
               'number_of_parallel_sets': 13,
               'wire_ground_size': '800',
               'wire_hot_size': '750',
               'wire_insulation': 'THWN',
               'wire_material': 'CU',
               'wire_service_ground_size': '2/0',
               'wire_temperature_rating': '75 C'}}}
